#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

###############################################################################
##                                AUTOSTART APPS                              #
###############################################################################

bspc monitor ^1 -s ^2 &
picom --experimental-backends --no-fading-openclose &
nitrogen --restore &
sh $HOME/.config/polybar/launch.sh &
dunst --config $HOME/.config/dunst/dunstrc &
lxqt-policykit-agent &
nm-applet &

###############################################################################
##                            GENERAL CONFIGURATION                           #
###############################################################################

bspc monitor DVI-D-0 -n 0 -d I II III IV V VI 
bspc monitor DVI-I-0 -n 1 -d VII VIII

bspc config border_width         0
bspc config window_gap           3

bspc config top_padding          0
bspc config bottom_padding       0

bspc config normal_border_color  "#282828"
bspc config active_border_color  "#282828"
bspc config focused_border_color "#282828"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


